spring.application.name=thiskostha
spring.datasource.url=jdbc:postgresql://localhost:5432/QuickCommerce
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sanjayreddygone01@gmail.com
spring.mail.password=mlms jdow rcpd vzba
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


myapp.api.key=pk.e13376a26985e3fd5361223a1ed9aabb
